const SPREADSHEETS = {
  MAIN: {
    ID: "1r93R3hKOCV6St4sac_88YZRM6OuYO9LxaxwMa2gWomE",
    SHEETS: {
      MAIN: "Principal"
    }
  },
  MONTHLY: {
    ID: "1nE0j6lgMZdimaLtO_31OKIpzVNNGBkVGB_xiPeAHoOw",
    ACCOUNT_SHEETS: [ACCOUNTS.ACCOUNT_1, ACCOUNTS.ACCOUNT_2, ACCOUNTS.ACCOUNT_3],
    CATEGORIES_SHEET: [CATEGORIES.CATEGORY_1.NAME, CATEGORIES.CATEGORY_2.NAME],
    CATEGORIES_MAIN_SHEET: "Categorías"
  }
}